import React from 'react'
import Head from 'next/head'
import { useState } from 'react'


const Server = () => {
  return (
    <div>
      <Head>
        <title>Server</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  )
}

export default Server