import Head from 'next/head'
import { useState, useEffect } from 'react'


const Server = () => {

  const [data, setData] = useState([])
  const [query, setQuery] = useState('')

  const keysForSearching = ['first_name', 'last_name', 'email'];

  const fetchData = async () => {
    // const url = 'http://localhost:3000/api/user'
    const url = '/api/user'
    const response = await fetch(url);
    const data = await response.json();
    setData(data);
  }

  useEffect(() => {
    fetchData();

  }, [])



  return (
    <div>
      <Head>
        <title>Server</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input
        type="text"
        className='inputField'
        placeholder='Searching...'
        onChange={e => setQuery(e.target.value.toLowerCase())}
      />


      <table>
        <tbody>
          <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
          </tr>

          {
            data.filter(user =>
              keysForSearching.some(key =>
                user[key].toLowerCase().includes(query)
              )).map(user => (

                <tr key={user.id}>

                  <td>{user.id}</td>
                  <td>{user.first_name}</td>
                  <td>{user.last_name}</td>
                  <td>{user.email}</td>

                </tr>
              ))
          }
        </tbody>
      </table>

    </div>
  )
}

export default Server