import Head from 'next/head'
import { useState } from 'react'
import { Users } from '../constants/userDB';

const Table = () => {

  const [query, setQuery] = useState('')

  const keysForSearching = ['first_name', 'last_name', 'email'];

  const search = () => {
    return Users.filter(user =>
      keysForSearching.some(key =>
        user[key].toLowerCase().includes(query)
      ))
  }

  return (
    <div>
      <Head>
        <title>Table</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input
        type="text"
        className='inputField'
        placeholder='Searching...'
        onChange={e => setQuery(e.target.value.toLowerCase())}
      />

      <table>
        <tbody>
          <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
          </tr>

          {
            // .slice(0, 20)

            Users.filter(user =>
              keysForSearching.some(key =>
                user[key].toLowerCase().includes(query)
              )).map(user => (

                <tr key={user.id}>

                  <td>{user.id}</td>
                  <td>{user.first_name}</td>
                  <td>{user.last_name}</td>
                  <td>{user.email}</td>

                </tr>
              ))
          }
        </tbody>
      </table>
    </div>
  )
}

export default Table