import Head from 'next/head'
import { useState } from 'react'
import Pagination from '../components/Pagination';
import { Users } from '../constants/userDB';

const Table = () => {

  const [query, setQuery] = useState('');
  const [data, setData] = useState(Users);
  const [currentPage, setCurrentPage] = useState(1);
  const [dataPerPage] = useState(10);

  const keysForSearching = ['first_name', 'last_name', 'email'];

  const indexOfLastData = currentPage * dataPerPage;
  const indexOfFirstData = indexOfLastData - dataPerPage;
  const currentData = data.slice(indexOfFirstData, indexOfLastData);

  const pageNumberClick = (number) => {
    setCurrentPage(number);
  }



  return (
    <div>
      <Head>
        <title>Table</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input
        type="text"
        className='inputField'
        placeholder='Searching...'
        onChange={e => setQuery(e.target.value.toLowerCase())}
      />

      <table>
        <tbody>
          <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
          </tr>

          {
            !query
              ? currentData.filter(user =>
                keysForSearching.some(key =>
                  user[key].toLowerCase().includes(query)
                )).map(user => (

                  <tr key={user.id}>

                    <td>{user.id}</td>
                    <td>{user.first_name}</td>
                    <td>{user.last_name}</td>
                    <td>{user.email}</td>

                  </tr>
                ))
              : data.filter(user =>
                keysForSearching.some(key =>
                  user[key].toLowerCase().includes(query)
                )).map(user => (

                  <tr key={user.id}>

                    <td>{user.id}</td>
                    <td>{user.first_name}</td>
                    <td>{user.last_name}</td>
                    <td>{user.email}</td>

                  </tr>
                ))
          }
        </tbody>
      </table>

      <div >
        <div >
          <Pagination
            totalData={data.length}
            dataPerPage={dataPerPage}
            pageNumberClick={pageNumberClick} />
        </div>
      </div>
    </div>
  )
}

export default Table